# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/guides/getting-started/language-go/ for more details
version: 2.1
orbs:
  go: circleci/go@4.0.0
jobs:
  build:
    executor:
      name: go/default
      tag: "1.22"
    environment:
      ENV: CI
      GO111MODULE: "on"
      INFLUXDB2_URL: "http://localhost:8086"
      INFLUXDB_URL: "http://localhost:8087"
      INFLUXDB2_ONBOARDING_URL: "http://localhost:8089"
    steps:
      - checkout
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
            mkdir -p /tmp/test-results
      - run: go version
      - go/with-cache:
          steps:
            - go/mod-download
      - run: make lint
      - run:
          name: "Start InfluxDB service"
          command: make server
      - run:
          command: make coverage
      - run:
          name: Collecting coverage reports
          command: |
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
            curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig
            curl -k https://uploader.codecov.io/verification.gpg | gpg --no-default-keyring --keyring trustedkeys.gpg --import
            gpgv codecov.SHA256SUM.sig codecov.SHA256SUM
            shasum -a 256 -c codecov.SHA256SUM
            chmod +x ./codecov
            ./codecov
      - store_artifacts:
          path: /tmp/artifacts
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results
workflows:
  main:
    jobs:
      - build
